// <auto-generated />
namespace Brain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestiftheconstructorisabadthingwiththeBookclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestiftheconstructorisabadthingwiththeBookclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201605231231418_Test if the constructor is a bad thing with the Book class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
